services:
  - type: web
    name: university-notice-backend
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.jxahlvgkxxmwnwoxaxja:[Ganesh123@]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
      - key: DATABASE_USER
        value: "postgres.jxahlvgkxxmwnwoxaxja"
      - key: DATABASE_PASSWORD
        value: "Ganesh123@"
      - key: FCM_SERVER_KEY
        value: "key=BKQv3nlwoRJm87d9o6g5Swxs8jj_dKZbqO3HGEC2BI6-_-Vq5x4NGGQeADMAqtOvLXAWfNv34gRMRMJVBEY0OB4"